title:               The Wall

# site url without a trailing '/'
# i.e. http://www.example.com
url:                 http://harshjv.github.io

# baseurl without a trailing '/'
# i.e. /my_project
baseurl:             ''
description:         Jekyll butler

paginate_path:       /blog/page/:num/
paginate:            15

permalink:           /blog/:title/

author:
  name:              Harsh Vakharia
  # Plain email or encoded email (http://ctrlq.org/encode/)
  email:             "&#104;&#097;&#114;&#115;&#104;&#106;&#118;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;"
  facebook:
    numeric_id:      1684195558
  docker:
    username:        harshjv
    link:            https://hub.docker.com/u/harshjv
  stackexchange:
    link:            http://stackexchange.com/users/1961153/harshjv
  google_plus:
    username:        HarshVakhariaJ
    link:            https://plus.google.com/+HarshVakhariaJ
  linkedin:
    username:        harshjv
    link:            http://in.linkedin.com/in/harshjv
  twitter:
    username:        harshjv
    link:            https://twitter.com/harshjv
  github:
    username:        harshjv
    link:            https://github.com/harshjv

disqus:
  shortname:         thewallbutler

google_analytics:
  id:                UA-60794187-2

sass:
  sass_dir:          _sass
  style:             :compressed

the_wall:
  link:              https://github.com/the-wall/butler
  version:           v1.0.0

exclude:             [vendor]
